dist: xenial
language: csharp
mono: none
dotnet: 2.2.203
addons:
  apt:
    packages:
      - powershell
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - pwsh ./test.ps1
cache:
  directories:
    - $HOME/.nuget/packages
